Adding single line output for base64 (#491)
When you have a bigger operation to patch, base64 will return output in multiple lines.

This will cause an error:
```
Error: got bad validating response: invalid character '\\n' in string literal
```

Which is hard to diagnose. Only having base64 output in oneliner makes it work correctly.